import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import { redirect } from "next/navigation";
import Head from "next/head";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const user = useUser();
  const router = useRouter();
  if (user.isSignedIn) router.push("/home");
  return (
    <>
      <Head>
        <title>Poker Backer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#000000] to-[#aa0000]">
        <header className="text-white">
          <SignInButton />
        </header>
      </main>
    </>
  );
};

export default Home;
