import { SignInButton } from "@clerk/nextjs";
import { useUser } from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const user = useUser();
  const router = useRouter();
  if (user.isSignedIn) void router.push("/home");
  return (
    <>
      <Head>
        <title>Poker Backer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <header className="">
          <SignInButton afterSignInUrl="/signup/new" />
        </header>
      </main>
    </>
  );
};

export default Home;
