import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const dashboard = api.backer.getDashboard.useQuery({
    id: "user_2OmeUZBsdKseCxgxXDbo7Pe0fLD",
  });
  const [backedPlayers, playerSessions] = dashboard.data ?? [null, null];

  return (
    <>
      <Head>
        <title>Poker Backer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="lg flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#000000] to-[#aa0000]">
        <header className="text-white">
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && <SignOutButton />}
        </header>
      </main>
    </>
  );
};

export default Home;
